"""Public country/area names, ISO alpha-2/alpha-3 codes and display regions.

UN M49: https://unstats.un.org/unsd/methodology/m49/ (retrieved 2026-09-27).
ISO code crosswalk: Debian iso-codes, iso_3166-1.json.
US is separated from Northern America; Taiwan is retained separately in Asia.
This is public reference metadata, never derived from a portfolio.
"""

COUNTRIES = (
    ('Afghanistan', 'AF', 'AFG', 'Asia'),
    ('Albania', 'AL', 'ALB', 'Europe'),
    ('Algeria', 'DZ', 'DZA', 'Africa'),
    ('American Samoa', 'AS', 'ASM', 'Oceania'),
    ('Andorra', 'AD', 'AND', 'Europe'),
    ('Angola', 'AO', 'AGO', 'Africa'),
    ('Anguilla', 'AI', 'AIA', 'Latin America & Caribbean'),
    ('Antarctica', 'AQ', 'ATA', 'Unknown geography'),
    ('Antigua and Barbuda', 'AG', 'ATG', 'Latin America & Caribbean'),
    ('Argentina', 'AR', 'ARG', 'Latin America & Caribbean'),
    ('Armenia', 'AM', 'ARM', 'Asia'),
    ('Aruba', 'AW', 'ABW', 'Latin America & Caribbean'),
    ('Australia', 'AU', 'AUS', 'Oceania'),
    ('Austria', 'AT', 'AUT', 'Europe'),
    ('Azerbaijan', 'AZ', 'AZE', 'Asia'),
    ('Bahamas', 'BS', 'BHS', 'Latin America & Caribbean'),
    ('Bahrain', 'BH', 'BHR', 'Asia'),
    ('Bangladesh', 'BD', 'BGD', 'Asia'),
    ('Barbados', 'BB', 'BRB', 'Latin America & Caribbean'),
    ('Belarus', 'BY', 'BLR', 'Europe'),
    ('Belgium', 'BE', 'BEL', 'Europe'),
    ('Belize', 'BZ', 'BLZ', 'Latin America & Caribbean'),
    ('Benin', 'BJ', 'BEN', 'Africa'),
    ('Bermuda', 'BM', 'BMU', 'Other North America'),
    ('Bhutan', 'BT', 'BTN', 'Asia'),
    ('Bolivia (Plurinational State of)', 'BO', 'BOL', 'Latin America & Caribbean'),
    ('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 'Latin America & Caribbean'),
    ('Bosnia and Herzegovina', 'BA', 'BIH', 'Europe'),
    ('Botswana', 'BW', 'BWA', 'Africa'),
    ('Bouvet Island', 'BV', 'BVT', 'Latin America & Caribbean'),
    ('Brazil', 'BR', 'BRA', 'Latin America & Caribbean'),
    ('British Indian Ocean Territory', 'IO', 'IOT', 'Africa'),
    ('British Virgin Islands', 'VG', 'VGB', 'Latin America & Caribbean'),
    ('Brunei Darussalam', 'BN', 'BRN', 'Asia'),
    ('Bulgaria', 'BG', 'BGR', 'Europe'),
    ('Burkina Faso', 'BF', 'BFA', 'Africa'),
    ('Burundi', 'BI', 'BDI', 'Africa'),
    ('Cabo Verde', 'CV', 'CPV', 'Africa'),
    ('Cambodia', 'KH', 'KHM', 'Asia'),
    ('Cameroon', 'CM', 'CMR', 'Africa'),
    ('Canada', 'CA', 'CAN', 'Other North America'),
    ('Cayman Islands', 'KY', 'CYM', 'Latin America & Caribbean'),
    ('Central African Republic', 'CF', 'CAF', 'Africa'),
    ('Chad', 'TD', 'TCD', 'Africa'),
    ('Chile', 'CL', 'CHL', 'Latin America & Caribbean'),
    ('China', 'CN', 'CHN', 'Asia'),
    ('China, Hong Kong Special Administrative Region', 'HK', 'HKG', 'Asia'),
    ('China, Macao Special Administrative Region', 'MO', 'MAC', 'Asia'),
    ('Christmas Island', 'CX', 'CXR', 'Oceania'),
    ('Cocos (Keeling) Islands', 'CC', 'CCK', 'Oceania'),
    ('Colombia', 'CO', 'COL', 'Latin America & Caribbean'),
    ('Comoros', 'KM', 'COM', 'Africa'),
    ('Congo', 'CG', 'COG', 'Africa'),
    ('Cook Islands', 'CK', 'COK', 'Oceania'),
    ('Costa Rica', 'CR', 'CRI', 'Latin America & Caribbean'),
    ('Croatia', 'HR', 'HRV', 'Europe'),
    ('Cuba', 'CU', 'CUB', 'Latin America & Caribbean'),
    ('Curaçao', 'CW', 'CUW', 'Latin America & Caribbean'),
    ('Cyprus', 'CY', 'CYP', 'Asia'),
    ('Czechia', 'CZ', 'CZE', 'Europe'),
    ('Côte d’Ivoire', 'CI', 'CIV', 'Africa'),
    ("Democratic People's Republic of Korea", 'KP', 'PRK', 'Asia'),
    ('Democratic Republic of the Congo', 'CD', 'COD', 'Africa'),
    ('Denmark', 'DK', 'DNK', 'Europe'),
    ('Djibouti', 'DJ', 'DJI', 'Africa'),
    ('Dominica', 'DM', 'DMA', 'Latin America & Caribbean'),
    ('Dominican Republic', 'DO', 'DOM', 'Latin America & Caribbean'),
    ('Ecuador', 'EC', 'ECU', 'Latin America & Caribbean'),
    ('Egypt', 'EG', 'EGY', 'Africa'),
    ('El Salvador', 'SV', 'SLV', 'Latin America & Caribbean'),
    ('Equatorial Guinea', 'GQ', 'GNQ', 'Africa'),
    ('Eritrea', 'ER', 'ERI', 'Africa'),
    ('Estonia', 'EE', 'EST', 'Europe'),
    ('Eswatini', 'SZ', 'SWZ', 'Africa'),
    ('Ethiopia', 'ET', 'ETH', 'Africa'),
    ('Falkland Islands (Malvinas)', 'FK', 'FLK', 'Latin America & Caribbean'),
    ('Faroe Islands', 'FO', 'FRO', 'Europe'),
    ('Fiji', 'FJ', 'FJI', 'Oceania'),
    ('Finland', 'FI', 'FIN', 'Europe'),
    ('France', 'FR', 'FRA', 'Europe'),
    ('French Guiana', 'GF', 'GUF', 'Latin America & Caribbean'),
    ('French Polynesia', 'PF', 'PYF', 'Oceania'),
    ('French Southern Territories', 'TF', 'ATF', 'Africa'),
    ('Gabon', 'GA', 'GAB', 'Africa'),
    ('Gambia', 'GM', 'GMB', 'Africa'),
    ('Georgia', 'GE', 'GEO', 'Asia'),
    ('Germany', 'DE', 'DEU', 'Europe'),
    ('Ghana', 'GH', 'GHA', 'Africa'),
    ('Gibraltar', 'GI', 'GIB', 'Europe'),
    ('Greece', 'GR', 'GRC', 'Europe'),
    ('Greenland', 'GL', 'GRL', 'Other North America'),
    ('Grenada', 'GD', 'GRD', 'Latin America & Caribbean'),
    ('Guadeloupe', 'GP', 'GLP', 'Latin America & Caribbean'),
    ('Guam', 'GU', 'GUM', 'Oceania'),
    ('Guatemala', 'GT', 'GTM', 'Latin America & Caribbean'),
    ('Guernsey', 'GG', 'GGY', 'Europe'),
    ('Guinea', 'GN', 'GIN', 'Africa'),
    ('Guinea-Bissau', 'GW', 'GNB', 'Africa'),
    ('Guyana', 'GY', 'GUY', 'Latin America & Caribbean'),
    ('Haiti', 'HT', 'HTI', 'Latin America & Caribbean'),
    ('Heard Island and McDonald Islands', 'HM', 'HMD', 'Oceania'),
    ('Holy See', 'VA', 'VAT', 'Europe'),
    ('Honduras', 'HN', 'HND', 'Latin America & Caribbean'),
    ('Hungary', 'HU', 'HUN', 'Europe'),
    ('Iceland', 'IS', 'ISL', 'Europe'),
    ('India', 'IN', 'IND', 'Asia'),
    ('Indonesia', 'ID', 'IDN', 'Asia'),
    ('Iran (Islamic Republic of)', 'IR', 'IRN', 'Asia'),
    ('Iraq', 'IQ', 'IRQ', 'Asia'),
    ('Ireland', 'IE', 'IRL', 'Europe'),
    ('Isle of Man', 'IM', 'IMN', 'Europe'),
    ('Israel', 'IL', 'ISR', 'Asia'),
    ('Italy', 'IT', 'ITA', 'Europe'),
    ('Jamaica', 'JM', 'JAM', 'Latin America & Caribbean'),
    ('Japan', 'JP', 'JPN', 'Asia'),
    ('Jersey', 'JE', 'JEY', 'Europe'),
    ('Jordan', 'JO', 'JOR', 'Asia'),
    ('Kazakhstan', 'KZ', 'KAZ', 'Asia'),
    ('Kenya', 'KE', 'KEN', 'Africa'),
    ('Kiribati', 'KI', 'KIR', 'Oceania'),
    ('Kuwait', 'KW', 'KWT', 'Asia'),
    ('Kyrgyzstan', 'KG', 'KGZ', 'Asia'),
    ("Lao People's Democratic Republic", 'LA', 'LAO', 'Asia'),
    ('Latvia', 'LV', 'LVA', 'Europe'),
    ('Lebanon', 'LB', 'LBN', 'Asia'),
    ('Lesotho', 'LS', 'LSO', 'Africa'),
    ('Liberia', 'LR', 'LBR', 'Africa'),
    ('Libya', 'LY', 'LBY', 'Africa'),
    ('Liechtenstein', 'LI', 'LIE', 'Europe'),
    ('Lithuania', 'LT', 'LTU', 'Europe'),
    ('Luxembourg', 'LU', 'LUX', 'Europe'),
    ('Madagascar', 'MG', 'MDG', 'Africa'),
    ('Malawi', 'MW', 'MWI', 'Africa'),
    ('Malaysia', 'MY', 'MYS', 'Asia'),
    ('Maldives', 'MV', 'MDV', 'Asia'),
    ('Mali', 'ML', 'MLI', 'Africa'),
    ('Malta', 'MT', 'MLT', 'Europe'),
    ('Marshall Islands', 'MH', 'MHL', 'Oceania'),
    ('Martinique', 'MQ', 'MTQ', 'Latin America & Caribbean'),
    ('Mauritania', 'MR', 'MRT', 'Africa'),
    ('Mauritius', 'MU', 'MUS', 'Africa'),
    ('Mayotte', 'YT', 'MYT', 'Africa'),
    ('Mexico', 'MX', 'MEX', 'Latin America & Caribbean'),
    ('Micronesia (Federated States of)', 'FM', 'FSM', 'Oceania'),
    ('Monaco', 'MC', 'MCO', 'Europe'),
    ('Mongolia', 'MN', 'MNG', 'Asia'),
    ('Montenegro', 'ME', 'MNE', 'Europe'),
    ('Montserrat', 'MS', 'MSR', 'Latin America & Caribbean'),
    ('Morocco', 'MA', 'MAR', 'Africa'),
    ('Mozambique', 'MZ', 'MOZ', 'Africa'),
    ('Myanmar', 'MM', 'MMR', 'Asia'),
    ('Namibia', 'NA', 'NAM', 'Africa'),
    ('Naoero', 'NR', 'NRU', 'Oceania'),
    ('Nepal', 'NP', 'NPL', 'Asia'),
    ('Netherlands (Kingdom of the)', 'NL', 'NLD', 'Europe'),
    ('New Caledonia', 'NC', 'NCL', 'Oceania'),
    ('New Zealand', 'NZ', 'NZL', 'Oceania'),
    ('Nicaragua', 'NI', 'NIC', 'Latin America & Caribbean'),
    ('Niger', 'NE', 'NER', 'Africa'),
    ('Nigeria', 'NG', 'NGA', 'Africa'),
    ('Niue', 'NU', 'NIU', 'Oceania'),
    ('Norfolk Island', 'NF', 'NFK', 'Oceania'),
    ('North Macedonia', 'MK', 'MKD', 'Europe'),
    ('Northern Mariana Islands', 'MP', 'MNP', 'Oceania'),
    ('Norway', 'NO', 'NOR', 'Europe'),
    ('Oman', 'OM', 'OMN', 'Asia'),
    ('Pakistan', 'PK', 'PAK', 'Asia'),
    ('Palau', 'PW', 'PLW', 'Oceania'),
    ('Panama', 'PA', 'PAN', 'Latin America & Caribbean'),
    ('Papua New Guinea', 'PG', 'PNG', 'Oceania'),
    ('Paraguay', 'PY', 'PRY', 'Latin America & Caribbean'),
    ('Peru', 'PE', 'PER', 'Latin America & Caribbean'),
    ('Philippines', 'PH', 'PHL', 'Asia'),
    ('Pitcairn', 'PN', 'PCN', 'Oceania'),
    ('Poland', 'PL', 'POL', 'Europe'),
    ('Portugal', 'PT', 'PRT', 'Europe'),
    ('Puerto Rico', 'PR', 'PRI', 'Latin America & Caribbean'),
    ('Qatar', 'QA', 'QAT', 'Asia'),
    ('Republic of Korea', 'KR', 'KOR', 'Asia'),
    ('Republic of Moldova', 'MD', 'MDA', 'Europe'),
    ('Romania', 'RO', 'ROU', 'Europe'),
    ('Russian Federation', 'RU', 'RUS', 'Europe'),
    ('Rwanda', 'RW', 'RWA', 'Africa'),
    ('Réunion', 'RE', 'REU', 'Africa'),
    ('Saint Barthélemy', 'BL', 'BLM', 'Latin America & Caribbean'),
    ('Saint Helena', 'SH', 'SHN', 'Africa'),
    ('Saint Kitts and Nevis', 'KN', 'KNA', 'Latin America & Caribbean'),
    ('Saint Lucia', 'LC', 'LCA', 'Latin America & Caribbean'),
    ('Saint Martin (French Part)', 'MF', 'MAF', 'Latin America & Caribbean'),
    ('Saint Pierre and Miquelon', 'PM', 'SPM', 'Other North America'),
    ('Saint Vincent and the Grenadines', 'VC', 'VCT', 'Latin America & Caribbean'),
    ('Samoa', 'WS', 'WSM', 'Oceania'),
    ('San Marino', 'SM', 'SMR', 'Europe'),
    ('Sao Tome and Principe', 'ST', 'STP', 'Africa'),
    ('Saudi Arabia', 'SA', 'SAU', 'Asia'),
    ('Senegal', 'SN', 'SEN', 'Africa'),
    ('Serbia', 'RS', 'SRB', 'Europe'),
    ('Seychelles', 'SC', 'SYC', 'Africa'),
    ('Sierra Leone', 'SL', 'SLE', 'Africa'),
    ('Singapore', 'SG', 'SGP', 'Asia'),
    ('Sint Maarten (Dutch part)', 'SX', 'SXM', 'Latin America & Caribbean'),
    ('Slovakia', 'SK', 'SVK', 'Europe'),
    ('Slovenia', 'SI', 'SVN', 'Europe'),
    ('Solomon Islands', 'SB', 'SLB', 'Oceania'),
    ('Somalia', 'SO', 'SOM', 'Africa'),
    ('South Africa', 'ZA', 'ZAF', 'Africa'),
    ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 'Latin America & Caribbean'),
    ('South Sudan', 'SS', 'SSD', 'Africa'),
    ('Spain', 'ES', 'ESP', 'Europe'),
    ('Sri Lanka', 'LK', 'LKA', 'Asia'),
    ('State of Palestine', 'PS', 'PSE', 'Asia'),
    ('Sudan', 'SD', 'SDN', 'Africa'),
    ('Suriname', 'SR', 'SUR', 'Latin America & Caribbean'),
    ('Svalbard and Jan Mayen Islands', 'SJ', 'SJM', 'Europe'),
    ('Sweden', 'SE', 'SWE', 'Europe'),
    ('Switzerland', 'CH', 'CHE', 'Europe'),
    ('Syrian Arab Republic', 'SY', 'SYR', 'Asia'),
    ('Taiwan', 'TW', 'TWN', 'Asia'),
    ('Tajikistan', 'TJ', 'TJK', 'Asia'),
    ('Thailand', 'TH', 'THA', 'Asia'),
    ('Timor-Leste', 'TL', 'TLS', 'Asia'),
    ('Togo', 'TG', 'TGO', 'Africa'),
    ('Tokelau', 'TK', 'TKL', 'Oceania'),
    ('Tonga', 'TO', 'TON', 'Oceania'),
    ('Trinidad and Tobago', 'TT', 'TTO', 'Latin America & Caribbean'),
    ('Tunisia', 'TN', 'TUN', 'Africa'),
    ('Turkmenistan', 'TM', 'TKM', 'Asia'),
    ('Turks and Caicos Islands', 'TC', 'TCA', 'Latin America & Caribbean'),
    ('Tuvalu', 'TV', 'TUV', 'Oceania'),
    ('Türkiye', 'TR', 'TUR', 'Asia'),
    ('Uganda', 'UG', 'UGA', 'Africa'),
    ('Ukraine', 'UA', 'UKR', 'Europe'),
    ('United Arab Emirates', 'AE', 'ARE', 'Asia'),
    ('United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', 'Europe'),
    ('United Republic of Tanzania', 'TZ', 'TZA', 'Africa'),
    ('United States Minor Outlying Islands', 'UM', 'UMI', 'Oceania'),
    ('United States Virgin Islands', 'VI', 'VIR', 'Latin America & Caribbean'),
    ('United States of America', 'US', 'USA', 'United States'),
    ('Uruguay', 'UY', 'URY', 'Latin America & Caribbean'),
    ('Uzbekistan', 'UZ', 'UZB', 'Asia'),
    ('Vanuatu', 'VU', 'VUT', 'Oceania'),
    ('Venezuela (Bolivarian Republic of)', 'VE', 'VEN', 'Latin America & Caribbean'),
    ('Viet Nam', 'VN', 'VNM', 'Asia'),
    ('Wallis and Futuna Islands', 'WF', 'WLF', 'Oceania'),
    ('Western Sahara', 'EH', 'ESH', 'Africa'),
    ('Yemen', 'YE', 'YEM', 'Asia'),
    ('Zambia', 'ZM', 'ZMB', 'Africa'),
    ('Zimbabwe', 'ZW', 'ZWE', 'Africa'),
    ('Åland Islands', 'AX', 'ALA', 'Europe'),
)
